### ISSUE TITLE
Glitched Out: Playtest 1 Feedback from Scott

### ISSUE THREAD

**Issue by scarrollrcad** [RinglingGameArt/2019_Senior_Thesis#85]
Most of the feedback was focused on the first half of the game.  We never made it to the third room:
Quit Button directs more viewer attention then Play Button.  Use shape, size, position and color to prioritize Play button.  The choice for blue is not the best.  Green means go.
Bug - lets talk to Flight school and figure out why the hands don't flex.
"What is an access panel?" - technically you can blowtorch everything - it's kinda fun but also does this introduce art and design scope issues?
Remove handles from panel. 
BUG - Panel can be pickup. ACK! 
Welding should be easier.  Remove corner segments as a requirement.  Visually they look weird anyway since they are diaganol cutting across the corners.

**Comment by tbivins** [comment]
Panel BUG is fixed: Handles are removed from the panel and wielding is easier to complete

**Comment by tbivins** [comment]
ANTs affected: The glue attachment slows down the ANT and the freeze bomb now freezes the ANTs

**Comment by tbivins** [comment]
Solved the issues
